// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVvXWQYF3TToq4ZWtL7CkqeXR4rlYJEyg',
    appId: '1:302130221629:web:4c66aefc2b172c100cd054',
    messagingSenderId: '302130221629',
    projectId: 'flutter-application-2934d',
    authDomain: 'flutter-application-2934d.firebaseapp.com',
    storageBucket: 'flutter-application-2934d.firebasestorage.app',
    measurementId: 'G-X31M7HS48L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgvjI1GrjTf98PS6xOS_XKHwZ8xt6ABEU',
    appId: '1:302130221629:android:9574883555335b8e0cd054',
    messagingSenderId: '302130221629',
    projectId: 'flutter-application-2934d',
    storageBucket: 'flutter-application-2934d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRyOheDaddbB9tc06u9u0ivlYWdqG3GSo',
    appId: '1:302130221629:ios:c3715b109e49297a0cd054',
    messagingSenderId: '302130221629',
    projectId: 'flutter-application-2934d',
    storageBucket: 'flutter-application-2934d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRyOheDaddbB9tc06u9u0ivlYWdqG3GSo',
    appId: '1:302130221629:ios:c3715b109e49297a0cd054',
    messagingSenderId: '302130221629',
    projectId: 'flutter-application-2934d',
    storageBucket: 'flutter-application-2934d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVvXWQYF3TToq4ZWtL7CkqeXR4rlYJEyg',
    appId: '1:302130221629:web:65f8b61a99d3f5b70cd054',
    messagingSenderId: '302130221629',
    projectId: 'flutter-application-2934d',
    authDomain: 'flutter-application-2934d.firebaseapp.com',
    storageBucket: 'flutter-application-2934d.firebasestorage.app',
    measurementId: 'G-98NHYRMY86',
  );
}
